### ISSUE TITLE
update `agoric/synthetic-chain` package version of `a3p-integration` proposals to latest (v0.3.0)

### ISSUE THREAD

**Issue by Jorge-Lopes** [Agoric/BytePitchPartnerEng#11]
# Objective

This ticket intend to update the `agoric/synthetic-chain` package of the a3p-integration `proposals` to the same version as it is declared on the `a3p-integration root` which is `v^0.3.0`, providing the tests with the most recent tools.

The proposals affected by the update are:
n:upgrade from ^0.1.0 to ^0.3.0
s:stake from ^0.1.0 to ^0.3.0
z:acceptance from ^0.2.1 to ^0.3.0

```[tasklist]
### Tasks
- [x] Update `a3p-integration/proposals/n:upgrade/package.json`
- [x] Update `a3p-integration/proposals/s:stake/package.json`
- [x] Update `a3p-integration/proposals/z:acceptance/package.json`
```
