### ISSUE TITLE
Extend `PSM` testing coverage

### ISSUE THREAD

**Issue by Jorge-Lopes** [Agoric/BytePitchPartnerEng#23]
Extend z:acceptance testing coverage of Vaults according to the functionalities identified on this [document](https://docs.google.com/document/d/1Irt0TScA1gVny63c64T8tdGwRTmM5kkNrqWJGacma1g/edit#heading=h.r3kpdmt4u0f)

```[tasklist]
### Tasks
- [ ] New user can complete a swap (smart wallet is provisioned during wallet spend action)
- [ ] User can complete a swap into IST 
- [ ] User can complete a swap out of IST 
- [ ] PSM minting limits are adhered to 
- [ ] Swap fee is added to swap
- [ ] User receives stable they are swapped into and their balance is deducted for amount they swapped for
```
