### ISSUE TITLE
Extend `Econ Gov` testing coverage

### ISSUE THREAD

**Issue by Jorge-Lopes** [Agoric/BytePitchPartnerEng#24]
Extend z:acceptance testing coverage of `Econ Gov` according to the functionalities identified on this [document](https://docs.google.com/document/d/1Irt0TScA1gVny63c64T8tdGwRTmM5kkNrqWJGacma1g/edit#heading=h.r3kpdmt4u0f)

Note: Some functionalities are already covered by existing test cases that are present in other test files. We intend to migrate them to this dedicated test file.

```[tasklist]
### Tasks
- [ ] For new EC members, EC member can accept invitation to charter and successfully propose and vote
- [ ] EC member can propose PSM or Vault contract or parameter change
- [ ] EC member can view active change proposals 
- [ ] EC member can vote on active change proposal
- [ ] EC member can see historical proposals  
- [ ] Proposal succeeds and is applied after quorum met and vote is successful 
- [ ] Configured EC parameters are intact following change or upgrade
```
