### ISSUE TITLE
migrate existing `wallet related` tests to z:acceptance

### ISSUE THREAD

**Issue by Jorge-Lopes** [Agoric/BytePitchPartnerEng#5]
**Effort Estimate:** 24 hours (3 days)
**Effort Required:** 8 hours (1 day)

**Dependencies:** Issue #4 

**Objective:**  
Migrate selected subset test cases from `a3p proposals` to the `z:acceptance` test phase and execute them to validate expected behavior.  

```[tasklist]
### Tasks
- [x] Select Test Cases for Migration
- [x] Incorporate selected tests to the `z:acceptance` test phase
- [x] Execute and confirm the expected behavior
```
