### ISSUE TITLE
refactor existing z:acceptance tests for uniformity in file extensions.

### ISSUE THREAD

**Issue by Jorge-Lopes** [Agoric/BytePitchPartnerEng#9]
**Effort Estimate:** 16 hours
**Effort Required:**

**Dependencies:** This issue overlaps with #8 

**Objective:** Ensure all test files use a standardized `.js` extension for uniformity across the codebase.

```[tasklist]
### Tasks
- [ ] refactor test-vaults.mts
- [ ] refactor create-kread-item-test.sh
- [ ] refactor genesis-test.sh
- [ ] Update test.sh
```

**Comment by Jorge-Lopes** [comment]
After rethinking this task, we concluded that:
- `test-vaults.mts` will be refactored into the `Econ-Gov` test that is detailed in the following [issue](https://github.com/Agoric/BytePitchPartnerEng/issues/24).
- `genesis-test.sh` should be kept as is because its implementation would not translate properly to an javascript test using the ava framework.
